specTestApp.Web/Controllers/RequestsController.cs
using specTestApp.Services.Interfaces;
using specTestApp.Services.Services;
using System;
using System.Web.Mvc;
using specTestApp.ViewModels;
using specTestApp.Web.Infrastructure;

namespace specTestApp.Web.Controllers
{
    [LogException]
    public class RequestsController : ControllerBase
    {
        private readonly IFileService _fileService;
        private readonly IRequestsService _requestsService;
        private readonly IUserService _userService;
        private readonly EmailService _emailService;

        public RequestsController()
        {
            IConfigurationProvider configurationProvider = new ConfigurationProvider();
            _fileService = new FileService();
            _requestsService = new RequestsService();
            _userService = new UserService();
            _emailService = new EmailService(configurationProvider);
        }

        [Authorize(Roles = "Manager")]
        public ActionResult RequestsList()
        {
            return View();
        }

        [Authorize(Roles = "Client")]
        public async System.Threading.Tasks.Task<ActionResult> Create()
        {
            var model = new CreateRequestViewModel();
            await CheckAbilityForCeationAsync(model);

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Client")]
        public async System.Threading.Tasks.Task<ActionResult> Create(CreateRequestViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                await CheckAbilityForCeationAsync(model);

                if (model.DenyCreation)
                {
                    ModelState.AddModelError("", model.DenyCreationReason);
                    return View(model);
                }

                var userName = User.Identity.Name;
                var user = await UserManager.FindByEmailAsync(userName);
                var folder = Server.MapPath("~/");

                var fileSaveResult = _fileService.SaveFile(model.File, folder);
                await _requestsService.CreateRequestAsync(model, fileSaveResult, user.Id);

                //Отправка новой заявки мэнэджэрам
                var managerEmails = await _userService.GetManagersEmails();
                await _emailService.SendAsync(model.Caption, model.Message, managerEmails);

                return RedirectToAction("Create");
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
                return View(model);
            }
        }

        private async System.Threading.Tasks.Task CheckAbilityForCeationAsync(CreateRequestViewModel model)
        {
            var userName = User.Identity.Name;
            var user = await UserManager.FindByEmailAsync(userName);

            if (!user.EmailConfirmed)
            {
                model.DenyCreation = true;
                model.DenyCreationReason = "Подтвердите Email перед созданием заявки";
                return;
            }

            var hours = await _requestsService.GetHoursFromLastRequestForUserAsync(user.Id);
            if (hours.HasValue && hours < 24)
            {
                model.DenyCreation = true;
                model.DenyCreationReason = $"{24 - hours.Value} ч. до создания новой заявки";
            }
        }
    }
}

specTestApp.Web/Views/Requests/Create.cshtml
@using specTestApp.Web.Models
@model  specTestApp.ViewModels.CreateRequestViewModel

@{
    ViewBag.Title = "Создать заявку";
}

<h2>@ViewBag.Title</h2>
<div class="row">
    <div class="col-md-8">
        <section>
            @using (Html.BeginForm("Create", "Requests", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <h4>Введите текст</h4>
                <hr />

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.Caption, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @if (!Model.DenyCreation)
                        {
                            @Html.TextBoxFor(m => m.Caption, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Caption, "", new { @class = "text-danger" })
                        }
                        else
                        {
                            @Html.TextBoxFor(m => m.Caption, new { @class = "form-control", disabled = "true" })
                        }
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Message, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @if (!Model.DenyCreation)
                        {
                            @Html.TextAreaFor(m => m.Message, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Message, "", new { @class = "text-danger" })
                        }
                        else
                        {
                            @Html.TextAreaFor(m => m.Message, new { @class = "form-control", disabled = "true" })
                        }
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="file" name="File" disabled="@Model.DenyCreation" />
                    </div>
                </div>

                <div class="form-group text">
                    <div class="col-md-offset-2 col-md-10">
                        @if (!Model.DenyCreation)
                        {
                            <input type="submit" class="btn btn-default" value="Создать заявку" />
                        }
                        else
                        {
                            <span class="label label-danger">@Model.DenyCreationReason</span>
                        }

                    </div>
                </div>
            }
        </section>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

specTestApp.Web/Views/Requests/RequestsList.cshtml

@{
  ViewBag.Title = "Список заявок";
}
<h2>@ViewBag.Title</h2>
<div class="row">
  <div class="col-md-12">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover table-sm text-center" style="background-color:white;">
        <thead>
          <tr>
            <th>ID</th>
            <th>Тема</th>
            <th>Сообщение</th>
            <th>Имя клиента</th>
            <th>Почта клиента</th>
            <th>Файл</th>
            <th>Время создания</th>
            <th class="text-center">Действия</th>
          </tr>
        </thead>
        <tbody id="container"></tbody>
        <tfoot>
          <tr>
            <th colspan="8" class="text-center">
              <button class="btn btn-sm btn-default" id="loadMoreButton">
                Загрузить ещё...
              </button>
              <span style="display:none" id="spinner">
                <i class="fa fa-refresh fa-spin fa-fw" aria-hidden="true"></i>
                <small class="text-muted">загрузка...</small>
              </span>
            </th>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>
@section Scripts {
  @Scripts.Render("~/bundles/jqueryval")
  <script>
    $(document).ready(function () {
      var itemsOnPage = 10;
      var skip = 0;
      var showInActive = false;
      var baseUrl = "/api/requestsapi/get";

      function showLoadingIndicator() {
        $('#spinner').css('display', 'inline');
        $('#loadMoreButton').css('display', 'none');
      }

      function hideLoadingIndicator() {
        $('#spinner').css('display', 'none');
        $('#loadMoreButton').css('display', 'inline');
      }

      $("#loadMoreButton").click(function () {
        load();
      });

      function load() {
        var url = formatRoute();
        showLoadingIndicator();
        var promise = $.get(url, function (data) {
            formatTable(data);
            skip = skip + itemsOnPage;
            hideLoadingIndicator();
          })
          .fail(function () {
            hideLoadingIndicator();
          });
      }

      function formatTable(data) {
        if (!data) {
          return;
        }

        data.forEach(function (item) {
          var tr = formatTableRow(item);
          $('#container').append(tr);
          $('#deactivate-' + item.RequestId).click(function (e) {
            deactivate(e.currentTarget);
          });
        });
      }

      function deactivate(el) {
        var data = $(el).data();
        if (!data) {
          return;
        }
        var requestId = data.val;
        var deleteUrl = "/api/requestsapi/delete/" + requestId;

        lockRemoveButton(el);

        $.ajax({
          type: "PUT",
          url: deleteUrl,
          success: function () {
            var tr = $(el).closest('tr');
            tr.fadeOut(700, function () {
              $(this).remove();
            });
          }
        });
      }

      function lockRemoveButton(el) {
        $(el).attr('disabled', 'disabled');
        var fa = $(el).find('.fa-ban');

        if (fa) {
          $(fa).removeClass('fa-ban');
          $(fa).addClass('fa-refresh');
          $(fa).addClass('fa-spin');
        }
      }

      function formatTableRow(item) {
        var tr = '<tr>';
        tr = tr + formatTableCell(item.RequestId);
        tr = tr + formatTableCell(item.Caption);
        tr = tr + formatTableCell(item.Message);
        tr = tr + formatTableCell(item.UserName);
        tr = tr + formatTableCell(item.UserName);
        tr = tr + formatFileUrl(item.FileUrl, item.OrigFileName);
        tr = tr + formatTableCell(item.CreationDateString);
        tr = tr + formatActionButton(item.RequestId);
        tr = tr + '</tr>';
        return tr;
      }

      function formatActionButton(id) {
        var b = '<button class="btn btn-sm btn-default" id="deactivate-' + id + '" data-val="' + id
          + '"> <i class="fa fa-ban fa-fw" aria-hidden="true"></i></button>';
        return '<td>' + b + '</td>';
      }

      function formatTableCell(cellData) {
        return '<td>' + cellData + '</td>';
      }

      function formatFileUrl(cellData, origFileName) {
        if (!cellData) {
          return '<td></td>';
        }
        var a = '<a';
        a = a + ' href=/' + cellData + '>';
        a = a + origFileName + '<a/>';
        return '<td>' + a + '</td>';
      }

      function formatRoute() {
        var route = baseUrl + '/' + itemsOnPage + '/' + skip + '/' + showInActive;
        return route;
      }

      load();
    });

  </script>
}